version: '3.8'

services:
  db:
    image: postgres:16
    container_name: el_music_db
    restart: always
    environment:
      - POSTGRES_USER=elmusic
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=elmusic_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
